### ISSUE TITLE
Send meaningful error message if a request is sent without a query

### ISSUE THREAD

**Issue by abhiaiyer91** [apollostack/graphql-server#112]
Was having a hard time debugging why a curl to my GraphQL server was not going through.

Was hit with `{"errors":[{"message":"Cannot read property 'definitions' of undefined"}]}`

Turns out i was not sending a query in my post body. Can we throw an error if a request is sent to the server with no query?

**Comment by joelgriffith** [comment]
What integration were you using? Some of them intelligently warn about missing POST bodies (generally a side-effect of not using a body-parser).

**Comment by jmurzy** [comment]
This should be fixed by graphql/graphql-js#614.

🍺

**Comment by helfer** [comment]
Good stuff @jmurzy ! 🙂
