### ISSUE TITLE
Write tests + documentation to explain how to use this package with restify

### ISSUE THREAD

**Issue by rricard** [apollostack/graphql-server#125]
Followup to #85.

Apollo Server works _out-of-the-box_ with [Restify](http://restify.com/) 🎉 .

We still need to ensure the compatibility with it: we need to ensure it won't break anytime soon so we need to provide both tests and documentation for this!

**Comment by helfer** [comment]
That's great news, thanks! Looking forward to the documentation and tests :)

**Comment by joelgriffith** [comment]
I'm interested in trying this out as well... Could you post what steps you've taken? I don't mind doing a PR for doc updates

**Comment by rricard** [comment]
@joelgriffith I couldn't work on that, but I can totally guide you in your contribution. The first thing to do, I think is to start with the tests: take the express tests and adapt them to use restify in there instead. Commit, push and create the pr early so I can help you along the way! 😉  Thank you!

**Comment by joelgriffith** [comment]
@rricard https://github.com/apollostack/apollo-server/pull/179 💥
