### ISSUE TITLE
Convert to monorepo

### ISSUE THREAD

**Issue by nnance** [apollostack/graphql-server#138]
Convert the repo to a monorepo like Babel and use the [lerna](https://lernajs.io/) tool to help manage publishing of each of the modules.

**Comment by DxCx** [comment]
i might take this if @helfer agrees with me on #124.

**Comment by nnance** [comment]
@DxCx so the expectation with this enhancement is to create separate npm modules for core, express, hapi and koa.  As a result, I would expect issue #124 will no longer be an issue or am I missing something?

**Comment by DxCx** [comment]
yes, as a result of that #124 is not needed because apollo-server will have flavors.
different won't mix the typings.

**Comment by helfer** [comment]
@DxCx: it's all yours!
