### ISSUE TITLE
"this" context or request data is unavailable from apolloKoa()

### ISSUE THREAD

**Issue by saeho** [apollostack/graphql-server#144]
Currently I cannot see the request data from:

```
Router.post('/graphql', apolloKoa(() => {...}));
```

It doesn't seem possible to get the request headers from apolloKoa().

**Comment by mikeifomin** [comment]
Koa 2 is supported I guess.

So headers contains in ctx object.
Related issue
https://github.com/apollostack/apollo-server/issues/139

And yes for now there is no way to pass the context data into options function. 
In express integration, for example, user(and other middleware state data) passed normal - [see GitHunt example](https://github.com/apollostack/GitHunt-API/blob/master/api/index.js#L68)

**Comment by helfer** [comment]
@saeho @mikeifomin What's the best way we can fix your problems?

cc @HriBB

**Comment by saeho** [comment]
Currently even though Apollo-Server supports Koa2, it really doesn't.

In order to allow authentication with each GraphQL query, we need to be able to pass some sort of token or auth info to the POST request's header. Then I need to be able to do something with that header info or pass it into the context. Currently Koa2 implementation of Apollo-Server does not make this possible.

Thus, Apollo-Server is unusable in Koa2.

**Comment by helfer** [comment]
@saeho Right, so how do we make it useable? Having access to it in the options function would be enough, right? I thought that was already the case, but I might be mistaken.

**Comment by saeho** [comment]
I stopped using ApolloKoa few days or a week ago but as far as I remember there was no way for me to see the header from the options function. So even though the ability to use a function to generate the options was there, I couldn't do anything with it.

**Comment by mikeifomin** [comment]
@helfer 
https://github.com/mikeifomin/apollo-server/commit/6584ac4ff369db09cc98c4c91b57a1c37e2892fd

**Comment by helfer** [comment]
@mikeifomin ok, I think we could just pass `ctx` instead as `ctx.request` as the only argument.

**Comment by mikeifomin** [comment]
@saeho  I'm working on app written with the KoaJS 2. And with the easy fix everything is ok and I have match cleaner resolvers with async/await style.

**Comment by mikeifomin** [comment]
@helfer your proposal looks better in case of "clean api". But it will break compatibility.

**Comment by helfer** [comment]
@mikeifomin true, although I think that's acceptable at this point. If you could make a PR, that would be great!

**Comment by migueloller** [comment]
@helfer and @saeho,

Looking forward to the change from just passing `request` to passing `ctx`. For now, this small change should work, though:
```js
Router.post('/graphql', (ctx, next) => apolloKoa(() => {...})(ctx, next));
```
That way you can use `ctx` however you want (e.g., pass it as GraphQL context) until this PR gets done.

**Comment by HriBB** [comment]
Hey. Sorry for the late reply, I'm really busy these days.

So if I understand this correctly, all that needs to be changed to resolve this issue is to pass `ctx` instead of `ctx.request` to the options object [here](https://github.com/apollostack/apollo-server/blob/master/src/integrations/koaApollo.ts#L28)?

**Comment by migueloller** [comment]
@HriBB, that's correct.

**Comment by HriBB** [comment]
[Here's](https://github.com/apollostack/apollo-server/pull/154) the PR. This is a breaking change, and we need to mention it in the changelog. @helfer let me know how to proceed.

**Comment by leebenson** [comment]
I'm currently orchestrating like this:

```js
router.post('/graphql',
  (context, next) => apolloKoa({
    schema,
    context,
  })(context, next),
);
```

This gives the 'full' context to the third parameter in my GraphQL queries, and makes `context.state` available (or, in fact,`context.*`)

Is there anything wrong with this approach? This pattern of orchestrating middleware in Koa2 is pretty common, when that same middleware needs access to ctx.state or ctx.request.

**Comment by DxCx** [comment]
Im not a koa expert but it looks like a decent solution..
