### ISSUE TITLE
Hapi: providing 'options' as a callback in 0.3.0

### ISSUE THREAD

**Issue by eugene1g** [apollostack/graphql-server#148]
(This is a documentation issue/google pointer more than a code issue)

Thanks for your work with refactoring the Hapi integration. One of the breaking changes in 0.3.0 is that providing a callback to Hapi's `options` parameter no longer seems to work. I use the callback option to extract auth from the HTTP header and with 0.2.0 this this worked -

```
options: request => {
    const userPersonId = extractUserFromRequest(request)
    console.log("Running request for ", userPersonId)
    return {
      schema: schema,
      formatError: (error) => ({
        message: error.message,
        stack: error.stack.split('\n'),
      }),
      context: {
        userPersonId: userPersonId
      }
    }
  }
```

So I thought with 0.3.0 I'll just wrap the return in `apolloOptions` might work like so -
```
options: request => {
    const userPersonId = extractUserFromRequest(request)
    console.log("Running request for ", userPersonId)
    return {
      apolloOptions: {  #new wrapper, perhaps? but no...
      schema: schema,
      formatError: (error) => ({
        message: error.message,
        stack: error.stack.split('\n'),
      }),
      context: {
        userPersonId: userPersonId
      }
      }
    }
  }
```

But doing that triggers an error message `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'formatError' of null`

So I looked through the integration code and found the answer - `options` can remain a plain object, and `apolloOptions` can be a callback or a promise, so this works -
```
options: {
    // Can be an async/promise callback as well
    apolloOptions: (request)=> {
      const userPersonId = extractUserFromRequest(request)
      console.log("Running request for ", userPersonId)
      return {
        schema: schema,
        formatError: (error) => ({
          message: error.message,
          stack: error.stack.split('\n'),
        }),
        context: {
          userPersonId: userPersonId
        }
      }
    }
  }
```

**Comment by nnance** [comment]
@eugene1g Thanks for the feedback, this is very useful.

**Comment by nnance** [comment]
@stubailo I have created the following PR to address this issue:

https://github.com/apollostack/tools-docs/pull/19

Once merged we should close this.
