### ISSUE TITLE
Forward (partial) query

### ISSUE THREAD

**Issue by sandervanhooft** [apollostack/graphql-server#155]
Is it possible to forward (part of) the graphql query to another service? I.e. ElasticSearch offers a (beta) GraphQL plugin. Is there a way to not have to parse the whole query in-depth on Apollo server, and just pass it on to ElasticSearch, get the result and return the result?

**Comment by helfer** [comment]
@sandervanhooft Parsing the whole query doesn't take much time (unless your query is huge). Letting another GraphQL server fulfill part of the query is definitely possible, but currently not trivial. You'd have to write a special resolver which sends the right part of your query to the ElasticSearch cluster by serializing it back (using the fourth argument to the resolve function). After that, graphql-js would still run the default resolver for every field returned from ElasticSearch, but you could probably hack something to make sure that's not the case.

**Comment by DxCx** [comment]
looks like this is well answered, reopen if the answer is insufficient

**Comment by morgs32** [comment]
@DxCx @helfer I'm trying to do this, serialize the query back together from the `info` argument - if you know off the top of your head a way to do this, please share!
