### ISSUE TITLE
Better params type annotation?

### ISSUE THREAD

**Issue by tonyxiao** [apollostack/graphql-server#157]
Was looking up the function signature of `formatParams` and `formatResponse` and realize that params is basically the same as the `queryOptions` type. Should we just make them the same type?

https://github.com/apollostack/apollo-server/blob/f4546e7654a2b12bb77ef5af407d89d1a62e8d6d/src/integrations/koaApollo.ts#L67-L79

``` typescript
        let params = {
          schema: optionsObject.schema,
          query: query,
          variables: variables,
          context: optionsObject.context,
          rootValue: optionsObject.rootValue,
          operationName: operationName,
          logFunction: optionsObject.logFunction,
          validationRules: optionsObject.validationRules,
          formatError: formatErrorFn,
          formatResponse: optionsObject.formatResponse,
          debug: optionsObject.debug,
        };
```

https://github.com/apollostack/apollo-server/blob/f4546e7654a2b12bb77ef5af407d89d1a62e8d6d/src/integrations/koaApollo.ts#L67-L79

``` typescript
export interface QueryOptions {
 schema: GraphQLSchema;
 query: string | Document;
 rootValue?: any;
 context?: any;
 variables?: { [key: string]: any };
 operationName?: string;
 logFunction?: LogFunction;
 validationRules?: Array<ValidationRule>;
 // WARNING: these extra validation rules are only applied to queries
 // submitted as string, not those submitted as Document!

 formatError?: Function;
 formatResponse?: Function;
 debug?: boolean;
}
```

**Comment by helfer** [comment]
@tonyxiao yeah, you're right, we should just make them the same type. Can you make PR?

**Comment by tonyxiao** [comment]
Need to get a bit more comfortable with TypeScript. But will do.

**Comment by DxCx** [comment]
params are passed to runQuery right after is defined.
runQuery requires QueryOptions, so, this is pretty much aligned.
