### ISSUE TITLE
Module '"graphql"' has no exported member 'GraphQLResult'.

### ISSUE THREAD

**Issue by gitawego** [apollostack/graphql-server#169]
in graphql typing, GraphQLResult is not an exported member. it throws error in typescript 2.x

**Comment by DxCx** [comment]
hi @gitawego,
this is working to me using typescript 2.0.6 compiler,
also, looking at the typings we are using (https://github.com/nitintutlani/typed-graphql/blob/master/graphql.d.ts#L12) it is clearly there.
can you please provide more info?

**Comment by DxCx** [comment]
no replay for a month now...
@gitawego did you manage? can we close the ticket?

**Comment by gitawego** [comment]
yes, sorry for the retard. I have another lib using the typing via @types/, which causes prob. it's resolved
