### ISSUE TITLE
Can I split queries and mutators across different files?

### ISSUE THREAD

**Issue by dcworldwide** [apollostack/graphql-server#190]
I'm trying to break up my schema into Entity specific classes, where each class defines the types, queries, mutators and resolvers specific to that Entity. Is this possible?

From the example, I can see that you can split Types and their resolves into seperate Entity specific files, but not queries/mutators?

**Comment by stubailo** [comment]
Hey, this issue belongs on graphql-tools, since Apollo server doesn't deal with generating schemas at all.

**Comment by dcworldwide** [comment]
Thanks, will move it.
