### ISSUE TITLE
Mutation which require an authenticated user

### ISSUE THREAD

**Issue by djhi** [apollostack/graphql-server#194]
Hi! I'm having a lot of of fun using apollo with koa and a react app :)

I have some mutations which require an authenticated user. I currently pass the user in the context and it works fine. However, I'd like to return an error with some status along with the error message. Here's my current resolver for this mutation:

``` js
async postOrder(root, { products }, { orderRepository, productRepository, user }) {
    if (!user) {
        const error = new Error('Not authorized');
        error.status = 401;
        throw error;
    }

    /* More code sanitizing products and creating the order */
}
```

I do get the error on client side, but only the message. The `status` property is lost. Moreover, it's a GraphQL error as it has been thrown from a resolver. Is there any way to send back a proper http status as it would make it easier to trigger specific behaviors on client side ?

**Comment by tadejstanic** [comment]
I was looking for the similar solution as you did, but couldn't find it. Then I came across with [this](https://medium.com/@tarkus/validation-and-user-errors-in-graphql-mutations-39ca79cd00bf#.3o60gi1w8) article and followed its recommendations. 

I think it'd be nice to have an option to somehow pass the error status, but on the other side, I assume that GraphQL error object is reserved for the errors which occurred at Graphql server level and not for those at the application level. Therefore we have to pass application error through custom error type and then parse it at the client side. Please, somebody corrects me if I'm wrong.

You can see my implementation of this error handling here [https://github.com/tadejstanic/graphql-api-example](https://github.com/tadejstanic/graphql-api-example)

**Comment by djhi** [comment]
Great, this is indeed a good solution. Thanks for sharing !
