### ISSUE TITLE
graphql-js containing Facebook's patents clause

### ISSUE THREAD

**Issue by bwhitty** [apollostack/graphql-server#197]
Hi all,

I'm wondering if there's been any discussion on this?

https://github.com/graphql/graphql-js/blob/master/PATENTS

This library transitively carries the same burden because of the dependency. Large companies are not going to be able to adopt this library (unless willingly accepting the risk) for any non-toy project with such a clause being included.

I wonder if MDG / Apollo harbors the same concern? With `graphql-js` being the sole JS implementation of an open source GQL server (unless I'm mistaken), do you think this hurts the adoptability of your library and with it the value prop of Apollo / Optics to larger enterprises?

Thanks ahead of time for any discussion.

**Comment by helfer** [comment]
The short answer to your question is: no, we're not concerned.

I was going to point you to this [thread](https://forums.meteor.com/t/react-facebook-patent-a-problem/21152/91), but I see you've already commented on it. We have not seen it being an issue at all for the many companies we've talked to, so we see no reason to be concerned.

It's also worth noting that neither Apollo Client nor Optics depend on graphql-js, and that there are GraphQL implementations in several languages that have very permissive open-source licences.

**Comment by bwhitty** [comment]
Hey Jonas, thanks for the quick reply. It's a reasonable position to take which I think answers the question here. I'll go ahead and close this.
