### ISSUE TITLE
GraphQL Authorization strategy with Connectors and Models

### ISSUE THREAD

**Issue by manuelfink** [apollostack/graphql-server#199]
## Wouldn't it make sense to provide a authorization recommendation/standardization with the models and connectors approach?

What I think of:

- providing a user context
- checking for rights
- how to throw errors on missing rights

The concept of [GraphQL Connectors and Models](https://github.com/apollostack/graphql-tools/blob/master/connectors.md) got described pretty well in the graphql-tools

@helfer pulished awesome posts on [how to authenticate in GraphQL](https://dev-blog.apollodata.com/a-guide-to-authentication-in-graphql-e002a4039d1#.52jbgb6vm) and [Authorization in GraphQL](https://dev-blog.apollodata.com/auth-in-graphql-part-2-c6441bcc4302#.lbg0nxnu8). The posts describe the basics of how authentication and authorization can be implemented. 

There are several approaches on how to provide an user context, but what I get from all readings so far, all end in similar results:

1. A user model implementing any kind of rights/acl/roles should be resolved (most likely by the middleware) and provided within the context
2. (Business) Model should check for rights (not the schema resolver)

**Comment by HriBB** [comment]
“Auth in GraphQL — Part 2” @helferjs https://dev-blog.apollodata.com/auth-in-graphql-part-2-c6441bcc4302

**Comment by stubailo** [comment]
I don't think there is something like this that could be standardized for all servers, but there are some ideas here: https://github.com/js-accounts/accounts
