### ISSUE TITLE
npm install graphql-server-express gives an error

### ISSUE THREAD

**Issue by martinwh99** [apollostack/graphql-server#200]
npm install graphql-server-express leads to the following error:

8118 error 404 Not Found
8118 error 404
8118 error 404 'types/express' is not in the npm registry.
8118 error 404 You should bug the author to publish it
8118 error 404 It was specified as a dependency of 'graphql-server-express'
8118 error 404
8118 error 404 Note that you can also install from a
8118 error 404 tarball, folder, or http url, or git url.
8119 error System Windows_NT 10.0.14393
8120 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "update"
8121 error cwd E:\dev_apollo\olts
8122 error node -v v6.3.1
8123 error npm -v 1.4.9
8124 error code E404

am i missing something?

regards
Martin

**Comment by DxCx** [comment]
Are you working against npm registry? Or against npm proxy?
I think proxy needs to be configured to support @scope packages..

**Comment by martinwh99** [comment]
I've tried different npm registry and still dit not manage it get it installed. I'm using meteor on a Win 10 PC. Here is my log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'graphql-server-express' ]
2 info using npm@1.4.9
3 info using node@v6.3.1
4 verbose readDependencies using package.json deps
5 verbose cache add [ 'graphql-server-express', null ]
6 verbose cache add name=undefined spec="graphql-server-express" args=["graphql-server-express",null]
7 verbose parsed url Url {
7 verbose parsed url   protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'graphql-server-express',
7 verbose parsed url   path: 'graphql-server-express',
7 verbose parsed url   href: 'graphql-server-express' }
8 silly lockFile 962c2763-graphql-server-express graphql-server-express
9 verbose lock graphql-server-express C:\Users\martin\AppData\Roaming\npm-cache\962c2763-graphql-server-express.lock
10 silly lockFile 962c2763-graphql-server-express graphql-server-express
11 silly lockFile 962c2763-graphql-server-express graphql-server-express
12 verbose addNamed [ 'graphql-server-express', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile bdda246d-graphql-server-express graphql-server-express@
15 verbose lock graphql-server-express@ C:\Users\martin\AppData\Roaming\npm-cache\bdda246d-graphql-server-express.lock
16 silly addNameRange { name: 'graphql-server-express', range: '*', hasData: false }
17 verbose url raw graphql-server-express
18 verbose url resolving [ 'https://registry.npmjs.org/', './graphql-server-express' ]
19 verbose url resolved https://registry.npmjs.org/graphql-server-express
20 info trying registry request attempt 1 at 09:28:53
21 verbose etag "3WIMR5QWAKUZW1CN3HZNE1FDW"
22 http GET https://registry.npmjs.org/graphql-server-express
23 http 304 https://registry.npmjs.org/graphql-server-express
24 silly registry.get cb [ 304,
24 silly registry.get   { date: 'Fri, 11 Nov 2016 08:28:53 GMT',
24 silly registry.get     via: '1.1 varnish',
24 silly registry.get     'cache-control': 'max-age=300',
24 silly registry.get     etag: '"3WIMR5QWAKUZW1CN3HZNE1FDW"',
24 silly registry.get     age: '0',
24 silly registry.get     connection: 'close',
24 silly registry.get     'x-served-by': 'cache-fra1235-FRA',
24 silly registry.get     'x-cache': 'HIT',
24 silly registry.get     'x-cache-hits': '1',
24 silly registry.get     'x-timer': 'S1478852933.586728,VS0,VE204',
24 silly registry.get     vary: 'Accept-Encoding' } ]
25 verbose etag graphql-server-express from cache
26 silly addNameRange number 2 { name: 'graphql-server-express', range: '*', hasData: true }
27 silly addNameRange versions [ 'graphql-server-express',
27 silly addNameRange   [ '0.4.0', '0.4.1', '0.4.2', '0.4.3' ] ]
28 verbose addNamed [ 'graphql-server-express', '0.4.3' ]
29 verbose addNamed [ '0.4.3', '0.4.3' ]
30 silly lockFile 3da8a2c6-graphql-server-express-0-4-3 graphql-server-express@0.4.3
31 verbose lock graphql-server-express@0.4.3 C:\Users\martin\AppData\Roaming\npm-cache\3da8a2c6-graphql-server-express-0-4-3.lock
32 silly lockFile 3da8a2c6-graphql-server-express-0-4-3 graphql-server-express@0.4.3
33 silly lockFile 3da8a2c6-graphql-server-express-0-4-3 graphql-server-express@0.4.3
34 silly lockFile bdda246d-graphql-server-express graphql-server-express@
35 silly lockFile bdda246d-graphql-server-express graphql-server-express@
36 silly resolved [ { name: 'graphql-server-express',
36 silly resolved     version: '0.4.3',
36 silly resolved     description: 'Production-ready Node.js GraphQL server for Express and Connect',
36 silly resolved     main: 'dist/index.js',
36 silly resolved     scripts: { compile: 'tsc', prepublish: 'npm run compile' },
36 silly resolved     repository:
36 silly resolved      { type: 'git',
36 silly resolved        url: 'https://github.com/apollostack/graphql-server/tree/master/packages/graphql-server-express' },
36 silly resolved     keywords:
36 silly resolved      [ 'GraphQL',
36 silly resolved        'Apollo',
36 silly resolved        'Server',
36 silly resolved        'Express',
36 silly resolved        'Connect',
36 silly resolved        'Javascript' ],
36 silly resolved     author: { name: 'Jonas Helfer', email: 'jonas@helfer.email' },
36 silly resolved     license: 'MIT',
36 silly resolved     bugs: { url: 'https://github.com/apollostack/graphql-server/issues' },
36 silly resolved     homepage: 'https://github.com/apollostack/graphql-server#readme',
36 silly resolved     dependencies:
36 silly resolved      { 'graphql-server-core': '^0.4.3',
36 silly resolved        'graphql-server-module-graphiql': '^0.4.3',
36 silly resolved        '@types/express': '^4.0.33' },
36 silly resolved     devDependencies:
36 silly resolved      { '@types/body-parser': '0.0.33',
36 silly resolved        '@types/connect': '^3.4.30',
36 silly resolved        '@types/express': '^4.0.33',
36 silly resolved        '@types/multer': '0.0.32',
36 silly resolved        'graphql-server-integration-testsuite': '^0.4.3',
36 silly resolved        'body-parser': '^1.15.2',
36 silly resolved        connect: '^3.4.1',
36 silly resolved        express: '^4.14.0',
36 silly resolved        multer: '^1.2.0',
36 silly resolved        'typed-graphql': '^1.0.2' },
36 silly resolved     peerDependencies: { graphql: '^0.6.1 || ^0.7.0' },
36 silly resolved     optionalDependencies: { '@types/express': '^4.0.33' },
36 silly resolved     typings: 'dist/index.d.ts',
36 silly resolved     typescript: { definition: 'dist/index.d.ts' },
36 silly resolved     readme: '# graphql-server-express\n\nThis is the Express and Connect integration for the Apollo community GraphQL Server. [Read the docs.](http://dev.apollodata.com/tools/apollo-server/index.html)\n',
36 silly resolved     readmeFilename: 'README.md',
36 silly resolved     _id: 'graphql-server-express@0.4.3',
36 silly resolved     _shasum: '198674e6db4949c060b9959554d3dc4e9cc4ed9b',
36 silly resolved     _from: 'graphql-server-express@',
36 silly resolved     _resolved: 'https://registry.npmjs.org/graphql-server-express/-/graphql-server-express-0.4.3.tgz' } ]
37 info install graphql-server-express@0.4.3 into E:\dev_apollo\reduxToast
38 info installOne graphql-server-express@0.4.3
39 info E:\dev_apollo\reduxToast\node_modules\graphql-server-express unbuild
40 verbose tar unpack C:\Users\martin\AppData\Roaming\npm-cache\graphql-server-express\0.4.3\package.tgz
41 silly lockFile 7ce97ff7-e-modules-graphql-server-express tar://E:\dev_apollo\reduxToast\node_modules\graphql-server-express
42 verbose lock tar://E:\dev_apollo\reduxToast\node_modules\graphql-server-express C:\Users\martin\AppData\Roaming\npm-cache\7ce97ff7-e-modules-graphql-server-express.lock
43 silly lockFile 14ae950f-server-express-0-4-3-package-tgz tar://C:\Users\martin\AppData\Roaming\npm-cache\graphql-server-express\0.4.3\package.tgz
44 verbose lock tar://C:\Users\martin\AppData\Roaming\npm-cache\graphql-server-express\0.4.3\package.tgz C:\Users\martin\AppData\Roaming\npm-cache\14ae950f-server-express-0-4-3-package-tgz.lock
45 silly gunzTarPerm modes [ '755', '644' ]
46 silly gunzTarPerm extractEntry package.json
47 silly gunzTarPerm extractEntry README.md
48 silly gunzTarPerm extractEntry dist/connectApollo.js
49 silly gunzTarPerm extractEntry dist/expressApollo.js
50 silly gunzTarPerm extractEntry dist/index.js
51 silly gunzTarPerm extractEntry dist/connectApollo.d.ts
52 silly gunzTarPerm extractEntry dist/connectApollo.js.map
53 silly gunzTarPerm extractEntry dist/expressApollo.d.ts
54 silly gunzTarPerm extractEntry dist/expressApollo.js.map
55 silly gunzTarPerm extractEntry dist/index.d.ts
56 silly gunzTarPerm extractEntry dist/index.js.map
57 silly lockFile 7ce97ff7-e-modules-graphql-server-express tar://E:\dev_apollo\reduxToast\node_modules\graphql-server-express
58 silly lockFile 7ce97ff7-e-modules-graphql-server-express tar://E:\dev_apollo\reduxToast\node_modules\graphql-server-express
59 silly lockFile 14ae950f-server-express-0-4-3-package-tgz tar://C:\Users\martin\AppData\Roaming\npm-cache\graphql-server-express\0.4.3\package.tgz
60 silly lockFile 14ae950f-server-express-0-4-3-package-tgz tar://C:\Users\martin\AppData\Roaming\npm-cache\graphql-server-express\0.4.3\package.tgz
61 info preinstall graphql-server-express@0.4.3
62 verbose readDependencies using package.json deps
63 verbose readDependencies using package.json deps
64 verbose cache add [ 'graphql-server-module-graphiql@^0.4.3', null ]
65 verbose cache add name=undefined spec="graphql-server-module-graphiql@^0.4.3" args=["graphql-server-module-graphiql@^0.4.3",null]
66 verbose parsed url Url {
66 verbose parsed url   protocol: null,
66 verbose parsed url   slashes: null,
66 verbose parsed url   auth: null,
66 verbose parsed url   host: null,
66 verbose parsed url   port: null,
66 verbose parsed url   hostname: null,
66 verbose parsed url   hash: null,
66 verbose parsed url   search: null,
66 verbose parsed url   query: null,
66 verbose parsed url   pathname: 'graphql-server-module-graphiql@%5E0.4.3',
66 verbose parsed url   path: 'graphql-server-module-graphiql@%5E0.4.3',
66 verbose parsed url   href: 'graphql-server-module-graphiql@%5E0.4.3' }
67 verbose cache add name="graphql-server-module-graphiql" spec="^0.4.3" args=["graphql-server-module-graphiql","^0.4.3"]
68 verbose parsed url Url {
68 verbose parsed url   protocol: null,
68 verbose parsed url   slashes: null,
68 verbose parsed url   auth: null,
68 verbose parsed url   host: null,
68 verbose parsed url   port: null,
68 verbose parsed url   hostname: null,
68 verbose parsed url   hash: null,
68 verbose parsed url   search: null,
68 verbose parsed url   query: null,
68 verbose parsed url   pathname: '%5E0.4.3',
68 verbose parsed url   path: '%5E0.4.3',
68 verbose parsed url   href: '%5E0.4.3' }
69 verbose addNamed [ 'graphql-server-module-graphiql', '^0.4.3' ]
70 verbose addNamed [ null, '>=0.4.3-0 <0.5.0-0' ]
71 silly lockFile da8ecac0-hql-server-module-graphiql-0-4-3 graphql-server-module-graphiql@^0.4.3
72 verbose lock graphql-server-module-graphiql@^0.4.3 C:\Users\martin\AppData\Roaming\npm-cache\da8ecac0-hql-server-module-graphiql-0-4-3.lock
73 verbose cache add [ '@types/express@^4.0.33', null ]
74 verbose cache add name=undefined spec="@types/express@^4.0.33" args=["@types/express@^4.0.33",null]
75 verbose parsed url Url {
75 verbose parsed url   protocol: null,
75 verbose parsed url   slashes: null,
75 verbose parsed url   auth: null,
75 verbose parsed url   host: null,
75 verbose parsed url   port: null,
75 verbose parsed url   hostname: null,
75 verbose parsed url   hash: null,
75 verbose parsed url   search: null,
75 verbose parsed url   query: null,
75 verbose parsed url   pathname: '@types/express@%5E4.0.33',
75 verbose parsed url   path: '@types/express@%5E4.0.33',
75 verbose parsed url   href: '@types/express@%5E4.0.33' }
76 verbose cache add [ 'graphql-server-core@^0.4.3', null ]
77 verbose cache add name=undefined spec="graphql-server-core@^0.4.3" args=["graphql-server-core@^0.4.3",null]
78 verbose parsed url Url {
78 verbose parsed url   protocol: null,
78 verbose parsed url   slashes: null,
78 verbose parsed url   auth: null,
78 verbose parsed url   host: null,
78 verbose parsed url   port: null,
78 verbose parsed url   hostname: null,
78 verbose parsed url   hash: null,
78 verbose parsed url   search: null,
78 verbose parsed url   query: null,
78 verbose parsed url   pathname: 'graphql-server-core@%5E0.4.3',
78 verbose parsed url   path: 'graphql-server-core@%5E0.4.3',
78 verbose parsed url   href: 'graphql-server-core@%5E0.4.3' }
79 verbose cache add name="graphql-server-core" spec="^0.4.3" args=["graphql-server-core","^0.4.3"]
80 verbose parsed url Url {
80 verbose parsed url   protocol: null,
80 verbose parsed url   slashes: null,
80 verbose parsed url   auth: null,
80 verbose parsed url   host: null,
80 verbose parsed url   port: null,
80 verbose parsed url   hostname: null,
80 verbose parsed url   hash: null,
80 verbose parsed url   search: null,
80 verbose parsed url   query: null,
80 verbose parsed url   pathname: '%5E0.4.3',
80 verbose parsed url   path: '%5E0.4.3',
80 verbose parsed url   href: '%5E0.4.3' }
81 verbose addNamed [ 'graphql-server-core', '^0.4.3' ]
82 verbose addNamed [ null, '>=0.4.3-0 <0.5.0-0' ]
83 silly lockFile b65222c8-graphql-server-core-0-4-3 graphql-server-core@^0.4.3
84 verbose lock graphql-server-core@^0.4.3 C:\Users\martin\AppData\Roaming\npm-cache\b65222c8-graphql-server-core-0-4-3.lock
85 verbose cache add name="" spec="types/express@^4.0.33" args=["","types/express@^4.0.33"]
86 verbose parsed url Url {
86 verbose parsed url   protocol: null,
86 verbose parsed url   slashes: null,
86 verbose parsed url   auth: null,
86 verbose parsed url   host: null,
86 verbose parsed url   port: null,
86 verbose parsed url   hostname: null,
86 verbose parsed url   hash: null,
86 verbose parsed url   search: null,
86 verbose parsed url   query: null,
86 verbose parsed url   pathname: 'types/express@%5E4.0.33',
86 verbose parsed url   path: 'types/express@%5E4.0.33',
86 verbose parsed url   href: 'types/express@%5E4.0.33' }
87 verbose cache add name="types/express" spec="^4.0.33" args=["types/express","^4.0.33"]
88 verbose parsed url Url {
88 verbose parsed url   protocol: null,
88 verbose parsed url   slashes: null,
88 verbose parsed url   auth: null,
88 verbose parsed url   host: null,
88 verbose parsed url   port: null,
88 verbose parsed url   hostname: null,
88 verbose parsed url   hash: null,
88 verbose parsed url   search: null,
88 verbose parsed url   query: null,
88 verbose parsed url   pathname: '%5E4.0.33',
88 verbose parsed url   path: '%5E4.0.33',
88 verbose parsed url   href: '%5E4.0.33' }
89 verbose addNamed [ 'types/express', '^4.0.33' ]
90 verbose addNamed [ null, '>=4.0.33-0 <5.0.0-0' ]
91 silly lockFile 133baa7c-types-express-4-0-33 types/express@^4.0.33
92 verbose lock types/express@^4.0.33 C:\Users\martin\AppData\Roaming\npm-cache\133baa7c-types-express-4-0-33.lock
93 silly addNameRange { name: 'graphql-server-module-graphiql',
93 silly addNameRange   range: '>=0.4.3-0 <0.5.0-0',
93 silly addNameRange   hasData: false }
94 silly addNameRange { name: 'graphql-server-core',
94 silly addNameRange   range: '>=0.4.3-0 <0.5.0-0',
94 silly addNameRange   hasData: false }
95 verbose url raw graphql-server-module-graphiql
96 verbose url resolving [ 'https://registry.npmjs.org/',
96 verbose url resolving   './graphql-server-module-graphiql' ]
97 verbose url resolved https://registry.npmjs.org/graphql-server-module-graphiql
98 info trying registry request attempt 1 at 09:28:53
99 verbose etag "83MI2U72C2U09UV1S838MXZZV"
100 http GET https://registry.npmjs.org/graphql-server-module-graphiql
101 silly addNameRange { name: 'types/express',
101 silly addNameRange   range: '>=4.0.33-0 <5.0.0-0',
101 silly addNameRange   hasData: false }
102 verbose url raw graphql-server-core
103 verbose url resolving [ 'https://registry.npmjs.org/', './graphql-server-core' ]
104 verbose url resolved https://registry.npmjs.org/graphql-server-core
105 info trying registry request attempt 1 at 09:28:53
106 verbose etag "52A6EHLLJ5FH6MENB70ZPH7IS"
107 http GET https://registry.npmjs.org/graphql-server-core
108 verbose url raw types/express
109 verbose url resolving [ 'https://registry.npmjs.org/', './types/express' ]
110 verbose url resolved https://registry.npmjs.org/types/express
111 info trying registry request attempt 1 at 09:28:53
112 http GET https://registry.npmjs.org/types/express
113 http 404 https://registry.npmjs.org/types/express
114 silly registry.get cb [ 404,
114 silly registry.get   { 'content-type': 'application/json',
114 silly registry.get     'cache-control': 'max-age=0',
114 silly registry.get     'content-length': '2',
114 silly registry.get     'accept-ranges': 'bytes',
114 silly registry.get     date: 'Fri, 11 Nov 2016 08:28:54 GMT',
114 silly registry.get     via: '1.1 varnish',
114 silly registry.get     age: '0',
114 silly registry.get     connection: 'close',
114 silly registry.get     'x-served-by': 'cache-fra1239-FRA',
114 silly registry.get     'x-cache': 'MISS',
114 silly registry.get     'x-cache-hits': '0',
114 silly registry.get     'x-timer': 'S1478852933.957836,VS0,VE117',
114 silly registry.get     vary: 'Accept-Encoding' } ]
115 silly lockFile 133baa7c-types-express-4-0-33 types/express@^4.0.33
116 silly lockFile 133baa7c-types-express-4-0-33 types/express@^4.0.33
117 verbose about to build E:\dev_apollo\reduxToast\node_modules\graphql-server-express
118 info E:\dev_apollo\reduxToast\node_modules\graphql-server-express unbuild
119 info preuninstall graphql-server-express@0.4.3
120 info uninstall graphql-server-express@0.4.3
121 verbose true,E:\dev_apollo\reduxToast\node_modules,E:\dev_apollo\reduxToast\node_modules unbuild graphql-server-express@0.4.3
122 info postuninstall graphql-server-express@0.4.3
123 error 404 Not Found
123 error 404
123 error 404 'types/express' is not in the npm registry.
123 error 404 You should bug the author to publish it
123 error 404 It was specified as a dependency of 'graphql-server-express'
123 error 404
123 error 404 Note that you can also install from a
123 error 404 tarball, folder, or http url, or git url.
124 error System Windows_NT 10.0.14393
125 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "graphql-server-express"
126 error cwd E:\dev_apollo\reduxToast
127 error node -v v6.3.1
128 error npm -v 1.4.9
129 error code E404
130 verbose exit [ 1, true ]

**Comment by stubailo** [comment]
It sounds like your computer has some problem with scoped npm.

Can you try just running:

```
npm install @types/express
```

And seeing if it works?

**Comment by DxCx** [comment]
I've seen this before when i used npm proxy with no scope support.
can you please try it against vanilla NPM first,
if it works, it means you need to configure/replace your proxy..

**Comment by martinwh99** [comment]
I've tried both, npm install @types/express and vanilla NPM still the same.

**Comment by martinwh99** [comment]
It works. the problem was the npm version. An update to the latest version solved the problem. Thanks for your help.
