### ISSUE TITLE
Errors in server console

### ISSUE THREAD

**Issue by mzygmunt** [apollostack/graphql-server#201]
Hi,
Is there any way to mute/catch error which appearing in the server console, when I run mutations which throws an error?

I've included a simple case on GitHub (https://github.com/mzygmunt/graphql-server-issue). When I run mutation, then I get the following error in the console:

![image](https://cloud.githubusercontent.com/assets/13297558/20158489/cdeb1fb8-a6da-11e6-9fec-36de29380200.png)

**Comment by Darkbladecr** [comment]
Experiencing the same, would find it useful to suppress these errors.

**Comment by helfer** [comment]
You can pass `debug: false` as part of the options, which should stop errors from being printed to the console. I have a feeling that maybe the option isn't documented yet...

**Comment by Darkbladecr** [comment]
You are right it is documented on [dev.apollodata.com](http://dev.apollodata.com/tools/graphql-server/setup.html#graphqlOptions). However it is missing from the Readme.md.
`// a boolean option that will trigger additional debug logging if execution errors occur
  debug?: boolean`

**Comment by mzygmunt** [comment]
@helfer It worked for me. Thanks

**Comment by netojose** [comment]
@helfer  For me too!!! thanks!!!
