### ISSUE TITLE
Publish new Version to NPM

### ISSUE THREAD

**Issue by Brainshack** [apollostack/graphql-server#202]
In the github repository, graphql-server package's latest release is v0.4.3 . On npm, the latest Version of graphql-server is 0.3.2. For the package apollo-server it is 0.3.3. Is there a reason for this?

**Comment by stubailo** [comment]
You should check out the installation directions: http://dev.apollodata.com/tools/graphql-server/index.html

Basically, neither the `apollo-server` or `graphql-server` packages should be used anymore. I still need to publish an official deprecation.

**Comment by helfer** [comment]
Just to clarify here: The `graphql-server` project is still very much alive, but it should be installed via one of the four server integration packages, eg. `graphql-server-express`, `graphql-server-hapi` etc.
