### ISSUE TITLE
Connecting to server session / auth cookie

### ISSUE THREAD

**Issue by simon2k** [apollostack/graphql-server#205]
Hi guys,

Do you have any solution for getting a current user or any info from session in the root value or in the context object?

Cheers

**Comment by helfer** [comment]
@simon2k I'm not sure what exactly you're asking for, but we recommend to do auth outside of GraphQL and simply adding the current user to the context. If you're looking for an example: here's how we do it in [GitHunt-API](https://github.com/apollostack/GitHunt-API/blob/master/api/index.js).

**Comment by chafnan** [comment]
@helfer Are there any examples of adding the user to the context for hapi?

**Comment by chafnan** [comment]
I found an answer.  

Turns out the `graphqlOptions` can be function.  Here is an example.

```javascript
server.register({
    register: graphqlHapi,
    options: {
      path: '/graphql',
      graphqlOptions: (request) => {
        return {
          schema: schema,
          context: {user: request.auth.credentials},
          debug: true,
        }
      },
      router: { cors: true },
      route: { auth: 'session' },
    }
  })
```

**Comment by DxCx** [comment]
correct. :)
