### ISSUE TITLE
[Docs] Production deployment recommendations

### ISSUE THREAD

**Issue by sandervanhooft** [apollostack/graphql-server#212]
Hi all,

How are you building and deploying graphql-server-express to Production? I can't find anything on this in the server docs.

Kind regards,

Sander

**Comment by rohanray** [comment]
@sandervanhooft I have been thinking about the same. I plan to run graphql-server-express on AWS or DO soon as a production app. I suggest that you move this question to the repo @ https://github.com/apollostack/tools-docs  or perhaps raise an issue over there too :) 

Production deployment guideline/recommendation from MDG or the core Apollo team would really help us a lot.

**Comment by helfer** [comment]
since it's open on the docs, I'll close it here.
