### ISSUE TITLE
How to avoid GraphQLError on Promise rejection

### ISSUE THREAD

**Issue by manuelfink** [apollostack/graphql-server#220]
Is it possible to reject an Promise on an GraphQL resolver and return an error to client without throwing an GraphQLError?

I have a root mutation which does an inserts in a table if an unique distinct element does not yet exits. E.g. signup of a new user. If the user already exists I reject the promise. Not sure if this is the right / best way? However in my mind reject() and throw new Error() are different things, but maybe I'm wrong?

The output on browser is as expected:

```
{
  "data": {
    "user": null
  },
  "errors": [
    {
      "message": "USER_ALLREADY_EXITS",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

However by default I get an output on console for every rejected promise like:

```
GraphQLError: USER_ALLREADY_EXITS
    at stack trace
```

Having an monitoring for errors on the console output makes this really annoying :/

**Comment by helfer** [comment]
@manuelfink Errors are only printed to the console in development mode. If you want to turn it off even in development mode, I believe you can pass the `debug: false` option.

**Comment by manuelfink** [comment]
@helfer thx. this brought up a view more questions, are there any docs on this?

 * How does Apollo GraphQL server determine development mode? 
 * Through node env variable? 
 * How is production mode turned on? 
 * That's the difference between production and development mode?
