### ISSUE TITLE
Custom scalars examples don't work

### ISSUE THREAD

**Issue by scf4** [apollostack/graphql-server#224]
The examples [http://dev.apollodata.com/tools/graphql-tools/scalars.html#Own-GraphQLScalarType-instance](here) don't seem to work. Am I missing something?

e.g.,
```javascript
import GraphQLJSON from 'graphql-type-json';

const resolvers = { ExampleCustomType: GraphQLJSON, ...etc };

export default makeExecutableSchema({ typeDefs, resolvers });
```

My resolver just returns `false`. I also tried creating my own types with new GraphQLScalarType({}) and got the same.

Then I find [this](https://github.com/graphql/graphql-js/issues/461) with the following example:

```javascript
Limit: {
    __description: '...',
    __parseValue(value) {
      return value;
    },
    __serialize(value) {
      return value;
    },
    __parseLiteral(ast) {
      ...
      return parsedLimit;
    },
  }
```

and `const resolvers = { ExampleCustomType: Limit, ..etc }` _works_.

I feel I must be missing something really obvious here?

**Comment by helfer** [comment]
@scf4 Thanks for reporting! Can you open this issue on graphql-tools please? It is not related to graphql-server.
