### ISSUE TITLE
mongodb returning fields limiting

### ISSUE THREAD

**Issue by sweetcharity** [apollostack/graphql-server#228]
Should I limit query results fields with ```{fields: {fieldExample: 0}}``` in mongoDB while using Apollo? I know that Apollo transit only what I need anyway, but is it better for server performance to limit returning fields in mongo too?

**Comment by jangerhofer** [comment]
This isn't really an Apollo-specific issue, but the answer appears to be **yes**, there are modest performance gains, given the [MongoDB docs here.](https://docs.mongodb.com/v3.2/tutorial/optimize-query-performance-with-indexes-and-projections/#use-projections-to-return-only-necessary-data)

**Comment by sweetcharity** [comment]
thx
