### ISSUE TITLE
graphql-server-express and graphql 0.8

### ISSUE THREAD

**Issue by callmephilip** [apollostack/graphql-server#234]
Is there any particular reason why graphql-server-express does not support graphql 0.8 (judging from [peerDependencies](https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-express/package.json#L44))

**Comment by Tallyb** [comment]
graphql is a dev dependency: 
https://github.com/apollostack/graphql-server/blob/master/package.json#L30
Is that intentional?

**Comment by Dattaya** [comment]
@Tallyb, it's not in all of the packages, e.g.: https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-express/package.json#L45

**Comment by helfer** [comment]
@callmephilip no particular reason. Feel free to make a PR, and I'll release a new version!

**Comment by delaneyj** [comment]
The npm registry needs to be updated and doesn't this actually update the version to 0.4.4 for the express package as well?

**Comment by callmephilip** [comment]
@helfer can you guys please publish the new version

**Comment by nicholaswyoung** [comment]
Ping. Can we get this released to npm?

**Comment by kachkaev** [comment]
ping 2 @helfer :–)

**Comment by ropsu** [comment]
ping-3 @helfer ;)

**Comment by helfer** [comment]
Sorry I dropped the ball on this one. There was a misunderstanding about who was going to release a new version. Making sure it happens now!
