### ISSUE TITLE
(regression?) Apollo-client throws when it receives error response 

### ISSUE THREAD

**Issue by thebigredgeek** [apollostack/graphql-server#236]
When error is returned:
<img width="1438" alt="screen shot 2016-12-06 at 3 37 10 pm" src="https://cloud.githubusercontent.com/assets/2799276/20948654/f87f949e-bbc9-11e6-9278-628318c72afb.png">
<img width="1439" alt="screen shot 2016-12-06 at 3 44 11 pm" src="https://cloud.githubusercontent.com/assets/2799276/20948811/ddbff184-bbca-11e6-9a44-621f193e38eb.png">
<img width="1436" alt="screen shot 2016-12-06 at 3 38 31 pm" src="https://cloud.githubusercontent.com/assets/2799276/20948668/174ed18c-bbca-11e6-81ae-70bbc955f6db.png">
<img width="1440" alt="screen shot 2016-12-06 at 3 38 38 pm" src="https://cloud.githubusercontent.com/assets/2799276/20948669/1751566e-bbca-11e6-9e4f-ed311be5bcb8.png">

When the mutation is successful:
<img width="1436" alt="screen shot 2016-12-06 at 3 41 26 pm" src="https://cloud.githubusercontent.com/assets/2799276/20948755/8703f61a-bbca-11e6-82ac-4611de2e13a7.png">
<img width="1433" alt="screen shot 2016-12-06 at 3 41 40 pm" src="https://cloud.githubusercontent.com/assets/2799276/20948759/8c715c96-bbca-11e6-94a7-ab839400b17f.png">
<img width="1437" alt="screen shot 2016-12-06 at 3 41 45 pm" src="https://cloud.githubusercontent.com/assets/2799276/20948760/8c84aaa8-bbca-11e6-855e-729fc106d4fd.png">

Looks like the client is expecting `result.data.customer` to at least be a valid path?

**Comment by stubailo** [comment]
Can you move the issue content to apollo-client? this definitely isn't related to the server.

Also, can you show the line in the code from `client.js` where the error is thrown from?

**Comment by thebigredgeek** [comment]
@stubailo not so sure.  The server was definitely returning a data prop in the response with errors a week ago.  it looks like this is no longer the case.

**Comment by thebigredgeek** [comment]
Unfortunately, I can't provide a stack trace into client.  Apollo client doesn't seem to work with webpack sourcemaps for whatever reason.  Any errors that apollo throws internally get swallowed like that without a valid source map.

**Comment by stubailo** [comment]
Depending on the error, the server may or may not include a `data` prop. Apollo should work either way, so it's certainly a client issue.
