### ISSUE TITLE
Latest release doesn't work with graphql ^0.8.0

### ISSUE THREAD

**Issue by estk** [apollostack/graphql-server#243]
Seems like someone has already done the work of upgrading since master has graphql ^0.8.2 in the root package.json, and  `"graphql": "^0.6.1 || ^0.7.0 || ^0.8.0"` in each project.

Not sure if it's ready, but it if so it would be great to cut a release.

**Comment by aikonplus** [comment]
Does not work for me too, get this error:
apollo-server@0.3.3 requires a peer of graphql@^0.6.1 || ^0.7.0 but none was installed.

and I have this in my package.json
"graphql": "^0.8.2"

**Comment by iwaldman** [comment]
Hi, any ETA?

**Comment by estk** [comment]
Seems like there's some interest... @stubailo, @helfer ?

**Comment by helfer** [comment]
@estk I think @nnance was going to cut a release shortly. 🙂

**Comment by coreygo** [comment]
Trying to work around this but currently unsuccessful. Friendly bump @helfer. Thanks :)

**Comment by helfer** [comment]
Should be all good now, folks. Sorry for the delay, there was a misunderstanding about who was going to release the next version 😞

**Comment by NitroBAY** [comment]
@helfer why do I still have `npm WARN apollo-server@0.3.3 requires a peer of graphql@^0.6.1 || ^0.7.0 but none was installed.` ?
Please also see the #291

**Comment by DxCx** [comment]
@NitroBAY,
You are using pretty old apollo-server,
Today, you should install the specific server package you need, for example, if you are using express, then install 'graphql-server-express'
More info is in README.md :)

**Comment by NitroBAY** [comment]
Okay, I was following [this](https://blog.meteor.com/create-a-simple-hello-world-app-with-meteor-and-apollo-64bab66a456f#.hto87me9e) tutorial. It asked to install apollo-server. BTW if you're in the team who wrote the tutorial please note that `export default PostsContainer = 'WHATEVS'` surprises me. It doesn't work as we can `export default 'WHATEVS'` but we cannot `export default variableName = 'WHATEVS'`. The point of export default is not to name what we export as default is already used as an identifier.

**Comment by masumbillah** [comment]
Anyone help me, when add this comd " yarn add apollo-server-express graphql-tools"

MSs-Mac-mini:twitter-app ms$ yarn add apollo-server-express graphql-tools
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "apollo-server-express > apollo-server-core@1.3.2" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > apollo-cache-control@0.0.9" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > apollo-tracing@0.1.3" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > graphql-extensions@0.0.7" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "graphql-tools > apollo-link@1.1.0" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".
warning " > graphql-tools@2.20.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0".
[4/4] 📃  Building fresh packages...
success Saved 2 new dependencies.
├─ apollo-server-express@1.3.2
└─ graphql-tools@2.20.2
✨  Done in 1.97s.
