### ISSUE TITLE
Batching and possibly using dataloader

### ISSUE THREAD

**Issue by smolinari** [apollostack/graphql-server#244]
Hi,

Is graphql-server's batching feature also doing the same thing as [Facebook's dataloader batching feature](https://github.com/facebook/dataloader)? If it is feature overlap, does that mean caching will also be available in graphql-server?

Scott

**Comment by DxCx** [comment]
No,
graphql-server batching feature lets it handle a batch of graphql queries.
dataloader's batcher actually hold off requests to the for data retrival and then pull them all at once.
2 different things.

**Comment by smolinari** [comment]
Ah. Ok. Then I need to learn more about graphql-server's batching feature.

Thanks for the reply!

Scott
