### ISSUE TITLE
GraphQL server & micro services

### ISSUE THREAD

**Issue by anhldbk** [apollostack/graphql-server#265]
I am sorry if you're bored with the following question. 

> Can GraphQL Server support miroservices?

So it will receive GraphQL requests and forward to micro services behind. We can use any technology to implement the services.

**Comment by TimMikeladze** [comment]
Your understanding is correct.

**Comment by DxCx** [comment]
ofcourse, eventually, Schema is executing resolvers, resolvers are just plain javascript code :)
