### ISSUE TITLE
Internal GraphQL requests within a resolver?

### ISSUE THREAD

**Issue by ericclemmons** [apollostack/graphql-server#266]
I have a specific `type LiveFeed` that would like to use GraphQL to fetch a larger tree & reduce it down.

Is there a way I can reuse `rootValue`, `context`, etc. from the existing request within the `LiveFeed` resolver and basically run `runQuery(...)` myself with a new `query` and `variables`?

**Comment by ericclemmons** [comment]
Ok, I was able to do some digging and figured out something like:

```js
import { runQuery } from "graphql-server-core";

...
    async LiveFeed(RootQuery, args, context, info) {
      const { data } = await runQuery({
        schema: info.schema,
        query: internalQuery, // TBD
        variables: internalVariables, // TBD
        context,
        rootValue: info.rootValue,
        // @NOTE These may not be necessary, or may be pulled from `info`
        // operationName: operationName,
        // logFunction: optionsObject.logFunction,
        // validationRules: optionsObject.validationRules,
        // formatError: formatErrorFn,
        // formatResponse: optionsObject.formatResponse,
        // debug: optionsObject.debug,
      });

      return reduce(data);
    },

**Comment by Migushthe2nd** [comment]
Is there an alternative to the `runQuery` function? It seems to have been removed. I came across `executeOperation`, but I can't seem to use this as the apolloserver instance hasn't been created when creating the schema.
