### ISSUE TITLE
integration with amqp

### ISSUE THREAD

**Issue by veeramarni** [apollostack/graphql-server#267]
We are wondering what would be the best way to have graphql server subscribe to amqp queues(such as  "graphql" queue name) so the microservices can run query and mutation by pushing requests to the queues.

**Comment by veeramarni** [comment]
Looks to be we can use `pubsub.subscribe` to subscribe to a AMQP queue. I will let everyone know how it goes. Please do let me know if there is a better way. 

We are working on below setup, in case anyone is curious. 
![image](https://cloud.githubusercontent.com/assets/3382355/21872618/65b483d8-d837-11e6-982b-ba19b244351c.png)

**Comment by DxCx** [comment]
@veeramarni any update? :)

**Comment by veeramarni** [comment]
Here is it. I need to update the documentation part.

https://github.com/cdmbase/graphql-server-rabbitmq

And the above one uses rabbitmq subscription

https://github.com/cdmbase/graphql-rabbitmq-subscriptions

**Comment by DxCx** [comment]
so @veeramarni the idea is to use the published apollo-subscription-ws to open subscriptions.
then this package will forward the subscriptions to RabitMQ?

**Comment by jayhuang75** [comment]
I'm in the same investigation, any idea where we can find some tutorials for understand clear the architecture? Thanks
