### ISSUE TITLE
Why @types/es6-shim and not these from TypeScript

### ISSUE THREAD

**Issue by kamilkisiela** [apollostack/graphql-server#279]
@DxCx

**Comment by DxCx** [comment]
what do you mean those from typescript?
we removed babel and now typescript compiles straight to es5.
you are welcome to open a PR to remove es6-shim if it's not needed. 👍

**Comment by DxCx** [comment]
Closed by #280

**Comment by kamilkisiela** [comment]
@DxCx Could we release it before `v0.10.0` of `apollo-angular`? :)))))))))

So I don't have to use `@types/es6-shim` and do non-standard things in tsconfig? https://github.com/kamilkisiela/apollo-angular-reproduction/pull/2/files

**Comment by DxCx** [comment]
Thats @helfer :)

**Comment by kamilkisiela** [comment]
@helfer :moneybag: :dollar:  :money_with_wings: :hourglass_flowing_sand:

**Comment by helfer** [comment]
Should I release?
