### ISSUE TITLE
Reference to es6-shim after change to TypeScript's es6 lib

### ISSUE THREAD

**Issue by Crevil** [apollostack/graphql-server#282]
After upgrading to `0.5.2` the dependency to `@types/es6-shim` was removed, but the packages still contains references to this module. It is only in the compiled and distributed packages I see it.

Here is `runHttpQuery.d.ts` from the `graphql-server-core` package:
```javascript
/// <reference types="@types/es6-shim" />
import { default as GraphQLOptions } from './graphqlOptions';
...
```

When installing `graphql-server-core` I get the following:
```
$ npm i graphql-server-core
/Users/a
├── UNMET PEER DEPENDENCY graphql@^0.6.1 || ^0.7.0 || ^0.8.0
└─┬ graphql-server-core@0.5.2
  ├── @types/graphql@0.8.6
  └── es6-shim@0.35.3
```

It seems the `graphql-server-core` is not published with the latest changes?

**Comment by DxCx** [comment]
Thanks @Crevil 
we have changed the reference right after 0.5.2 was released.
we will probably launch another release soon. :)

**Comment by Crevil** [comment]
@dxcx Got it. Looking forward to it and keep up the great stuff the whole team is putting into these projects.
