### ISSUE TITLE
graphql-server-hapi don't forward route options properly.

### ISSUE THREAD

**Issue by jorgecuesta** [apollostack/graphql-server#284]
Hi guys, I try to send some plugins options on:
`options.route = { plugins: { myPlugin: {} } }`

But you are doing:
```javascript
Object.assign(options.route || {}, {
        plugins: {
            graphql: isOptionsFunction(options.apolloOptions) ? options.apolloOptions : () => options.apolloOptions,
        }
...
})
```
With this result config just have your plugins settings because it replace my custom settings. Same things with pre: []. 

Maybe if you use a merge like lodash can solve this little issue.

Best Regards,

**Comment by jorgecuesta** [comment]
I replace Object.assign with Hoek.merge an it work perfect. Just need this replace and add require statement. 
```js
const Hoek = require('hoek');
```

**Comment by DxCx** [comment]
Hi @jorgecuesta Thanks for reporting! can you please submit a PR with a failing test and a fix, perferredly without an extra dependancy..

**Comment by jorgecuesta** [comment]
@DxCx Thanks for quickly response. Don't worry about it. I have an old version v0.3.2 of apollo-server found on npm. Now I use graphql-server-hapi an this issue does not happen.
