### ISSUE TITLE
Error 400: Bad Request (message: Must provide document)

### ISSUE THREAD

**Issue by semanser** [apollostack/graphql-server#286]
Hi all. Previously have created the same issue in `apollo-client` https://github.com/apollostack/apollo-client/issues/1233, but @calebmer has mentioned that it could be `graphql-server` problem.  
I have pretty simple graphql-server: 

```js
import express from 'express'
import bodyParser from 'body-parser'
import { graphqlExpress, graphiqlExpress } from 'graphql-server-express'
import { makeExecutableSchema, addResolveFunctionsToSchema } from 'graphql-tools'

import Schema from './schema'
import Resolvers from './resolvers'

const executableSchema = makeExecutableSchema({
  typeDefs: Schema,
  printErrors: true,
});

addResolveFunctionsToSchema(executableSchema, Resolvers)

const PORT = 3000;
const app = express();

app.use('/graphql', bodyParser.json(), graphqlExpress(
  {
    schema: executableSchema,
    resolvers: Resolvers,
  },
))
app.use('/graphiql', graphiqlExpress({ endpointURL: '/graphql' }))

app.listen(PORT, () => console.log('Server is running!'))
```

With `graphiql` tool everything working correctly: I can make requests and receive expected results. But when I am trying to send request with `apollo-client`, something wrong. Here is my client code:

```js
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import gql from 'graphql-tag';

const apolloClient = new ApolloClient({
  networkInterface: createNetworkInterface({
    uri: 'http://localhost:3000/graphql',
    opts: {
      mode: 'no-cors',
    },
  }),
});

const query = gql`
  {
    polls {
      title
    }
  }
`

apolloClient.query({
  query,
}).then(result => {
  console.log(result)
})
```

Here is errors: 

![123](https://cloud.githubusercontent.com/assets/4020045/22339471/c4a49de4-e3f2-11e6-86f6-ecd0098bdc43.png)

Here is request details and response:
![2017-01-26 18 11 45](https://cloud.githubusercontent.com/assets/4020045/22339574/190e2332-e3f3-11e6-8312-7e82ac37d0e8.png)
![2017-01-26 18 11 55](https://cloud.githubusercontent.com/assets/4020045/22339594/2bb1b314-e3f3-11e6-94eb-0dc1bd24d752.png)

I am using next versions: 
```
    "apollo-client": "^0.8.0",
    "graphql": "^0.9.0",
    "graphql-server-express": "^0.5.2",
    "graphql-tag": "^1.2.3",
    "graphql-tools": "^0.9.2",
```

**Comment by helfer** [comment]
@semanser You need to pass resolvers into `makeExecutableSchema`, not into `graphqlExpress`. Apart from that, the error indicates that the query doesn't make it through to graphql-js.

**Comment by semanser** [comment]
@helfer still doesn't work... Anyway, why is there two ways to pass resolvers? Which is more correctly?

**Comment by DxCx** [comment]
resolvers key in makeExectuableSchema instad of calling addResolveFunctions...

**Comment by semanser** [comment]
@DxCx thanks, changed. So currently my code looks like this, but I am still get the same error. Also the strange thing that with `graphiql` everything working correctly.

```js
import express from 'express'
import bodyParser from 'body-parser'
import { graphqlExpress, graphiqlExpress } from 'graphql-server-express'
import { makeExecutableSchema } from 'graphql-tools'

import Schema from './schema'
import Resolvers from './resolvers'

const executableSchema = makeExecutableSchema({
  typeDefs: Schema,
  printErrors: true,
  resolvers: Resolvers,
});

const PORT = 3000;
const app = express();

app.use('/graphql', bodyParser.json(), graphqlExpress(
  {
    schema: executableSchema,
  },
))
app.use('/graphiql', graphiqlExpress({ endpointURL: '/graphql' }))
app.listen(PORT, () => console.log('Server is running!'))
```

**Comment by semanser** [comment]
In my opinion it can be problem with client side, not `graphql-server`. The reason is that I can send requests with `graphqli and receive correct responses. But when I use `ApolloClient` something goes wrong.

**Comment by helfer** [comment]
@semanser I agree, most likely your client setup is wrong. Please reopen the issue there!

**Comment by automatiche** [comment]
n my case, I forgot to handle the encryption and decryption settings of the interface parameters
